# Generated by Django 3.0.5 on 2020-06-09 06:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='num_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='short_url',
            field=models.URLField(default=datetime.datetime(2020, 6, 9, 6, 5, 13, 843634, tzinfo=utc), max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storage',
            name='long_url',
            field=models.URLField(unique=True),
        ),
    ]
