# Generated by Django 3.0.5 on 2020-06-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0002_auto_20200609_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='long_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='storage',
            name='short_url',
            field=models.URLField(max_length=6, unique=True),
        ),
    ]
