# Generated by Django 3.0.5 on 2020-06-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0003_auto_20200612_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='long_url',
            field=models.URLField(null=True),
        ),
    ]
